### ISSUE TITLE
Coordinate Array Error

### ISSUE THREAD

**Issue by nilsleh** [smartin98/Global_DL_SSH#1]
@smartin98 Thank you for the very intriguing paper and open sourcing the code. After reading, I wanted to understand the data generation process a bit more and was looking at the `generate_global_data.py` script.  From the code it seems that [here](https://github.com/smartin98/Global_DL_SSH/blob/b19e0411897ce5fadc6ae777a884d7d23a118e9a/generate_global_data.py#L119) regions is assumed to be a 4D array, however, the `ocean_coords` generated beforehand that and saved to `coords_grid.npy` is a 2D array. Also when trying to run this part of the code, I get an array index error. I was therefore wondering if you could help me understand what I am missing. Thanks in advance!

**Comment by smartin98** [comment]
@nilsleh Thanks for your interest in the code! Good spot, there was actually a bug. It should be fixed now using the extra script calculate_coord_grids.py before running generate_global_data.py I just commited. Hope that helps!

Just FYI, the implementation in this repo is not user-friendly, so apologies in advance if you run into problems working through this - especially with generate_global_data.py as this script is very slow right now.  I'm in the process of making a more streamlined workflow [here](https://github.com/smartin98/NeurOST) but it's still a work in progress.
