### ISSUE TITLE
bathymetry.npy files not found

### ISSUE THREAD

**Issue by nilsleh** [smartin98/Global_DL_SSH#3]
The `generate_global_data.py` script generates all the data to the enumerated subdirectories. In the next pipeline step, when looking at the processing of the ML input/output pairs, [this line](https://github.com/smartin98/Global_DL_SSH/blob/e7e1a021a5326763390f37bef4c2344685baf32c/pre_process_training.py#L170) is expecting a `bathymetry.npy` file, however, I do not see it being saved in the `generate_global_data.py` script. Is there a separate script for this? Thanks in advance!

**Comment by smartin98** [comment]
Sorry, this was a reference to an older version of the code where I was including bathymetry as a predictor. Hopefully it's fixed now, I went through and removed the inconsistent parts and cleaned things up a bit. Let me know if this issue isn't fixed by my latest commit.
